spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lookback
    username: lookback
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

tmdb:
  access-token: ${TMDB_ACCESS_TOKEN}