CREATE TABLE movies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tmdb_id INTEGER NOT NULL UNIQUE,
    title VARCHAR(300) NOT NULL,
    original_title VARCHAR(300),
    overview TEXT,
    release_date DATE,
    budget BIGINT,
    revenue BIGINT,
    runtime_minutes INTEGER,
    popularity DOUBLE PRECISION,
    vote_average NUMERIC(4, 2),
    vote_count INTEGER,
    poster_path VARCHAR(500),
    backdrop_path VARCHAR(500),
    original_language VARCHAR(10),
    adult BOOLEAN NOT NULL DEFAULT FALSE,
    last_updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT movies_budget_nonnegative
        CHECK (budget IS NULL OR budget > 0),

    CONSTRAINT movies_revenue_nonnegative
        CHECK (revenue IS NULL OR revenue > 0),

    CONSTRAINT movies_runtime_nonnegative
        CHECK (runtime_minutes IS NULL OR runtime_minutes >= 0),

    CONSTRAINT movies_vote_average_range
        CHECK (
            vote_average IS NULL
            OR vote_average BETWEEN 0 AND 10
        ),

    CONSTRAINT movies_vote_count_nonnegative
        CHECK (vote_count IS NULL OR vote_count >= 0)
);

CREATE TABLE genres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tmdb_genre_id INTEGER NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE movie_genres (
    movie_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,

    PRIMARY KEY (movie_id, genre_id),

    CONSTRAINT movie_genres_movie_fk
        FOREIGN KEY (movie_id)
        REFERENCES movies (id)
        ON DELETE CASCADE,

    CONSTRAINT movie_genres_genre_fk
        FOREIGN KEY (genre_id)
        REFERENCES genres (id)
        ON DELETE CASCADE
);

CREATE INDEX movies_title_index
    ON movies (title);

CREATE INDEX movies_release_date_index
    ON movies (release_date);

CREATE INDEX movies_popularity_index
    ON movies (popularity DESC);

CREATE INDEX movies_rating_index
    ON movies (vote_average DESC, vote_count DESC);

CREATE INDEX movie_genres_genre_index
    ON movie_genres (genre_id);